### ISSUE TITLE
Error with get.oturep with latest release

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#575]
Hi,

I had a code running the `get.oturep()` command of my clustered sequences using the `abundance` method (using mothur v.1.41.1). However, with the new release, I now get a segmentation fault when I try to do the same command:

`get.oturep(count=current, fasta=current, list=current, method=abundance, label=0.03)`

By changing back to the previous version, I was able to successfully run the code
Do you know where it could come from?

Thanks,
Cedric

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug. I corrected the issue and uploaded a new version of 1.41.2, https://github.com/mothur/mothur/releases/tag/v1.41.21. Can you give it a try?

**Comment by Puumanamana** [comment]
Thanks, that was quick. Works perfectly now!

**Comment by koopkaup** [comment]
Using the latest version (1.43.0) I still get a segfault when method is abundance. I clustered my sequences with dgc method.

**Comment by mothur-westcott** [comment]
I am not seeing that with the test files. I ran the following with 1.43.0:

mothur > get.oturep(list=final.opti_mcc.list, count=final.count_table, fasta=final.fasta, method=abundance, cutoff=0.03)
0.03	479

Output File Names: 
/Users/sarahwestcott/desktop/release/final.opti_mcc.0.03.rep.count_table
/Users/sarahwestcott/desktop/release/final.opti_mcc.0.03.rep.fasta

Could you post the log file from your run?

mothur > quit()

**Comment by koopkaup** [comment]
My commands:
```
unique.seqs(fasta=MOCK.fasta)
make.table(name=current)
cluster(fasta=current, count=current, cutoff=0.03, method=dgc)
get.oturep(list=MOCK.unique.dgc.list, count=MOCK.count_table, fasta=MOCK.unique.fasta, method=abundance, cutoff=0.03)
```

End of the logfile:
```
mothur > cluster(fasta=current, count=current, cutoff=0.03, method=dgc)
Using mock/MOCK.count_table as input file for the count parameter.
Using mock/MOCK.unique.fasta as input file for the fasta parameter.
vsearch v2.9.1_linux_x86_64, 62.7GB RAM, 40 cores
https://github.com/torognes/vsearch

Reading file MOCK.unique.fasta.sorted.fasta.temp 100%
20092272 nt in 57242 seqs, min 100, max 476, avg 351
Masking 100%
Counting k-mers 100%
Clustering 100%
Sorting clusters 100%
Writing clusters 100%
Clusters: 3492 Size min 1, max 7579, avg 16.4
Singletons: 2482, 4.3% of seqs, 71.1% of clusters

Using 40 processors.

0.03
It took 66 seconds to cluster

Output File Names: 
mock/MOCK.unique.dgc.list

/var/spool/slurm/slurmd/job6758753/slurm_script: line 27: 35223 Segmentation fault      (core dumped) mothur mothur.batch
```

**Comment by mothur-westcott** [comment]
Could you send the MOCK.fasta file to mothur.bugs@gmail.com so I can take a closer look?

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue and sending your files. I found the source of the problem. Mothur did not account for a count file without groups in the get.oturep command. I have fixed it and will add the change to the official 1.43.0 release, coming soon. In the meantime, here's a simple workaround:

unique.seqs(fasta=mock.fasta)
make.group(fasta=mock.fasta, groups=group1)
make.table(name=current, group=current)
cluster(fasta=mock.unique.fasta, count=current, cutoff=0.03, method=dgc)
get.oturep(list=current, fasta=current, count=current, method=abundance, cutoff=0.03)
