### ISSUE TITLE
Debian smoke test fails on 1.44.0

### ISSUE THREAD

**Issue by thinred** [mothur/mothur#717]
(Debian package maintainer here)
I've noticed that the version 1.44.0 fails the smoke test (with "Segmentation fault"), but the test worked well on 1.42.1. See:

  * https://ci.debian.net/data/autopkgtest/unstable/amd64/m/mothur/5353578/log.gz
  * https://ci.debian.net/data/autopkgtest/unstable/amd64/m/mothur/4870966/log.gz

The issue happens after the line "Using HA.unique.fn.list as input file for the list parameter.".

The test is simple: https://salsa.debian.org/med-team/mothur/-/blob/master/debian/tests/run-unit-test

Best,
Tomasz

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. We have corrected it in version 1.44.1, https://github.com/mothur/mothur/releases/tag/v.1.44.1. Could you give it a try?

**Comment by thinred** [comment]
I packaged the newer version and released it in Debian. It doesn't seem to have helped, the segmentation fault still occurs. I will debug where that happens exactly, but cannot give any ETA on this.

P.S. I noticed that the tags you put on the releases are a bit inconsistent; I've missed the most recent release, because of that: the tag is "v.1.44.1" whereas the previous ones were "1.44.0", "v.1.43.0", "v1.43.0", each having a slightly different structure. I improved my regexp and it should catch these cases now.

**Comment by mothur-westcott** [comment]
Thanks for helping us find this segfault bug. Mothur's smart distancing was not working quite right and crashed when it couldn't find the exact match for the label requested. I have resolved this and you can download the fixed source code from the master branch. It will be included in our next release.

**Comment by thinred** [comment]
Oh, great! Thanks!
I prefer to wait for an official release rather than use master.

I'll close this bug in the meantime.
