### ISSUE TITLE
Issues regarding Indicator, chimera.vsearch and rarefaction.shared

### ISSUE THREAD

**Issue by caiorachid** [mothur/mothur#729]
I'm an experient user of Mothur. I use it to teach my students how to analyse 16S sequences.
I noticed 4 bugs in this new version (1.44.1). I am using linux RedHat 7

1 - chimera.vsearch only produce a count_table file if "dereplicate=T"

===================================

2 - rarefaction.shared did not work properly. 
mothur > rarefaction.shared(shared=final.opti_mcc.shared, design=design2.txt)

Using 32 processors.
0.03
0.03
0.03

Output File Names: 
final.opti_mcc.groups.rarefaction

Looking the output. It has no 0.03-(sample) value only 1, 2, 3, 4 and 5, and the lci numbers are higher then hci.

numsampled	0.03-N	lci-N	hci-N	0.03-O	lci-O	hci-O	0.03-Y	lci-Y	hci-Y
1	1.000000	426.395000	382.000000	1.000000	520.006000	489.000000	1.000000	533.295000	500.000000
2	2.000000	610.280000	551.000000	2.000000	742.243000	697.000000	2.000000	752.870000	706.000000
3	3.000000	716.685000	668.000000	3.000000	887.482000	828.000000	3.000000	898.230000	881.000000
4	4.000000	807.545000	784.000000	4.000000	990.469000	948.000000	4.000000	1009.725000	1002.000000
5	5.000000	860.000000	860.000000	5.000000	1063.000000	1063.000000	5.000000	1089.000000	1089.000000

The same command, with the same file worked just fine with version 1.42.3:
mothur > rarefaction.shared(shared=final.opti_mcc.shared, design=design2.txt)

Using 32 processors.
0.03	N
0.03	O
0.03	Y

Output File Names: 
final.opti_mcc.groups.rarefaction

Looking the output

numsampled	0.03-N	lci-N	hci-N	0.03-O	lci-O	hci-O	0.03-Y	lci-Y	hci-Y
1	416.000000	416.000000	416.000000	516.944000	489.000000	591.000000	528.213000	500.000000	546.000000
2	617.000000	617.000000	617.000000	753.064000	697.000000	784.000000	753.218000	706.000000	771.000000
3	720.000000	720.000000	720.000000	896.632000	828.000000	917.000000	899.922000	881.000000	919.000000
4	815.000000	815.000000	815.000000	995.904000	948.000000	1008.000000	1010.415000	1002.000000	1023.000000
5	860.000000	860.000000	860.000000	1063.000000	1063.000000	1063.000000	1089.000000	1089.000000	1089.000000

===================================

3 - Indicator is not working at all.
See the examples:

"mothur > indicator(shared=final.opti_mcc.shared, design=design2.txt, groups=Y-O)
You did not provide a label, I will use the first label in your inputfile.

Using 32 processors.

Species	Indicator_Groups	IndicatorValue	pValue
Otu0026	C13-C14-C15-C16-C17	76.8817	0.041
Otu0067	C13-C14-C15-C16-C17	83.2	0.04
Otu0118	C13-C14-C15-C16-C9	86.4197	0.039
Otu0176	C13-C14-C15-C16-C17	90.625	0.031
Otu0197	C13-C14-C15-C16-C17	92	0.008

It took 0 secs to find the indicator species.

Output File Names: 
final.opti_mcc.indicator.summary"

It mixed samples from one group to another (C13-C14-C15-C16 is used with C17 AND with C9)
The design2 file is the following:

group   treat
C10     Y
C11     Y
C12     Y
C13     O
C14     O
C15     O
C16     O
C17     O
C18     N
C19     N
C20     N
C21     N
C22     N
C8      Y
C9      Y

Also when I run specifying some samples, it included some samples I did not select:
See:
mothur > indicator(shared=final.opti_mcc.shared, design=design2.txt, groups=C8-C9-C10-C11-C12-C13-C14-C15-C16-C17)
You did not provide a label, I will use the first label in your inputfile.

Using 32 processors.

Species	Indicator_Groups	IndicatorValue	pValue
Otu0001	C18-C19-C20-C21-C22	46.2585	0.033
Otu0003	C18-C19-C20-C21-C22	47.0418	0.027
Otu0007	C18-C19-C20-C21-C22	89.0774	0.029
Otu0010	C18-C19-C20-C21-C22	73.4637	0.022
Otu0011	C18-C19-C20-C21-C22	45.1043	0.048
Otu0013	C18-C19-C20-C21-C22	50.9967	0.023
Otu0019	C18-C19-C20-C21-C22	56.7619	0.027
Otu0021	C18-C19-C20-C21-C22	66.6023	0.019
Otu0026	C18-C19-C20-C21-C22	60.4255	0.028
Otu0029	C18-C19-C20-C21-C22	58.2716	0.041
Otu0030	C18-C19-C20-C21-C22	70.7921	<0.001
Otu0031	C18-C19-C20-C21-C22	57.0352	0.015
Otu0037	C18-C19-C20-C21-C22	79.6657	0.013
Otu0038	C18-C19-C20-C21-C22	69.6629	0.013
Otu0044	C18-C19-C20-C21-C22	69.1318	<0.001
Otu0059	C18-C19-C20-C21-C22	64.7368	0.015
Otu0060	C18-C19-C20-C21-C22	90.5759	0.013
Otu0063	C18-C19-C20-C21-C22	61.1111	0.035
Otu0067	C18-C19-C20-C21-C17	62.6506	0.025
...

I did, the same using an old Version (1.39.5), and it worked just fine!
mothur > indicator(shared=final.opti_mcc.shared, design=design, groups=Y-O)
You did not provide a label, I will use the first label in your inputfile.

Using 1 processors.

Species	Indicator_Groups	IndicatorValue	pValue
Otu0007	C13-C14-C15-C16-C17	89.320389	0.031000
Otu0008	C13-C14-C15-C16-C17	83.876495	0.032000
Otu0020	C13-C14-C15-C16-C17	78.057549	0.035000
Otu0026	C13-C14-C15-C16-C17	76.881721	0.026000
Otu0030	C13-C14-C15-C16-C17	85.593224	0.034000
Otu0033	C13-C14-C15-C16-C17	82.156128	0.045000
Otu0036	C13-C14-C15-C16-C17	77.914116	0.027000
Otu0039	C13-C14-C15-C16-C17	75.842705	0.030000
Otu0049	C10-C11-C12-C8-C9	90.495872	0.042000
Otu0065	C10-C11-C12-C8-C9	72.033897	0.027000
Otu0066	C13-C14-C15-C16-C17	90.217392	0.014000
Otu0067	C13-C14-C15-C16-C17	83.199997	0.027000
Otu0074	C10-C11-C12-C8-C9	87.162170	0.038000
Otu0105	C10-C11-C12-C8-C9	96.385536	0.033000
Otu0118	C10-C11-C12-C8-C9	86.419746	0.040000
Otu0130	C10-C11-C12-C8-C9	84.415588	0.033000
Otu0146	C13-C14-C15-C16-C17	68.965515	0.026000
Otu0153	C13-C14-C15-C16-C17	90.000000	0.033000
Otu0155	C10-C11-C12-C8-C9	89.830513	0.036000
.....
===================================

4 - The program crashes if you press enter without any command.

**Comment by mothur-westcott** [comment]
Thank you for reporting these issues.

1. The chimera.vsearch command only creates a new count file when the dereplicate parameter is set to true intentionally. When dereplicate=F, any sequence found to be chimeric in any sample is added to the accnos file for removal with the remove.seqs command. When dereplicate=T, sequences are flagged as chimeric within their group rather than throughout the dataset. Mothur creates a count file with the chimeric reads removed from the samples they were found to be chimeric in and left in the samples they were not found to be chimeric in.

2. The rarefaction.shared was not assembling the group file correctly. I have fixed this issue and the change will be part of our next release.

3. The indicator command is working as designed.  The groups parameter is designed to allow you to enter the sets you wish to include, not samples. Let me explain:

mothur > indicator(shared=final.opti_mcc.shared, design=design, groups=Y-O) - selects samples from sets Y and O.

mothur > indicator(shared=final.opti_mcc.shared, design=design2.txt, groups=C8-C9-C10-C11-C12-C13-C14-C15-C16-C17) - attempts to select sets named C8-C9-C10-C11-C12-C13-C14-C15-C16-C17, but does not find any since these are sample names. The groups parameter is ignored and all sets are used in the calculation.

Instead try this:

mothur >  get.groups(shared=final.opti_mcc.shared, design=design2.txt, groups=C8-C9-C10-C11-C12-C13-C14-C15-C16-C17) - select samples to include
mothur > indicator(shared=current, design=current) - run indicator on subset of samples


4.  I will take a closer look at the crash on enter.

**Comment by caiorachid** [comment]
Dear Sarah,

Thank you for your answer and for your time developing Mothur for our community.

I understood the problems 1,  2 and 4.

However, the indicator still seams like an issue to me.
For Exemple, when I run "indicator(shared=final.opti_mcc.shared, design=design, groups=Y-O)”, shouldn’t the program contrast samples (C8-C9-C10-C11-C12) Versus (C13–C14-C15-C16-C17)?
Taking in account the design file is the following?
group treat
C10 Y
C11 Y
C12 Y
C13 O
C14 O
C15 O
C16 O
C17 O
C18 N
C19 N
C20 N
C21 N
C22 N
C8 Y
C9 Y

The output didn’t do it. It mixed, for exemple, sample C9 (from Y) with C16 (O).

However, using the version 1.39.5 with the same files, it worked as I suppose it meant to work.

Like this: 
Species Indicator_Groups IndicatorValue pValue
Otu0007 C13-C14-C15-C16-C17 89.320389 0.031000
Otu0008 C13-C14-C15-C16-C17 83.876495 0.032000
Otu0020 C13-C14-C15-C16-C17 78.057549 0.035000
Otu0026 C13-C14-C15-C16-C17 76.881721 0.026000
Otu0030 C13-C14-C15-C16-C17 85.593224 0.034000
Otu0033 C13-C14-C15-C16-C17 82.156128 0.045000
Otu0036 C13-C14-C15-C16-C17 77.914116 0.027000
Otu0039 C13-C14-C15-C16-C17 75.842705 0.030000
Otu0049 C10-C11-C12-C8-C9 90.495872 0.042000

Also the number of OTUs flagged as indicator was quite different from one version to another.

Thank you very much,
Kind regards,
Caio Rachid

Caio Rachid, PhD
----------------------------------------------------------------------------------
Associate Professor
LABEM - Laboratory of Biotechnology and Microbial Ecology
Institute of Microbiology
Federal University of Rio de Janeiro
Phone:+55 21 98446-7664
Phone +55 21 3938-6741
https://labem.microbiologia.ufrj.br/
----------------------------------------------------------------------------------

**Comment by mothur-westcott** [comment]
Could you send your shared, design and log files to mothur.bugs@gmail.com so I can take a closer look?

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug and sending your files. I was able to find the source of the difference between 1.39.5 and 1.44.1. The randomization was not working properly, which in turn produced incorrect pvalues. I have fixed the issue and will put out a 1.44.2 release later this week with the change included.

**Comment by caiorachid** [comment]
Dear Sarah,
Here I am again (sorry)!
Regarding the rarefaction.shared command, It appears that we still have an issue.
I am running this data again (it is part of a course I teach in the university), and the output is not correct.
My dataset has 3 treatments (Y, N and O), each one with 5 samples. Mothur recognize all three, but the labels in the output file shows only one (Y).
Additionally, it calculates values for only four samples per treatment, instead of the correct 5.
<img width="1001" alt="image" src="https://github.com/mothur/mothur/assets/8798117/e089b3a5-15a2-4e7d-bac3-ff2044492cfb">
<img width="598" alt="image" src="https://github.com/mothur/mothur/assets/8798117/2ceae9cd-b970-49d3-afb2-787185532170">

Warm regards and thanks a lot for your work in improving Mothur!

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug! It is not an issue in the calculations, just the labels. The numsampled column data should start at two, not one and go until all samples have been added. I have also fixed the column labels in the *.groups.rarefaction file.  The change is currently in the master branch, and will be included in our next release.
